# This is a basic workflow that is dev triggered

name: social-media auto deploy to server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:  # 手动执行工作流
  push:
    branches:
      - main  # main分支push时自动执行工作流
    paths:
      - 'social_media/**'  # 只有social_media目录变化时才触发
      - '.github/workflows/social-media-deploy.yml'  # workflow文件变化时也触发
      - '!social_media/**/*.md'  # 排除md文件变化

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 下载源码
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 安装依赖
    - name: Install Dependencies
      working-directory: ./social_media
      run: |
        rm -rf node_modules package-lock.json
        npm install

    # 打包正式环境
    - name: Build
      working-directory: ./social_media
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.0.3
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TEST_2BRAIN_KEY }}
        REMOTE_HOST: ${{ secrets.TEST_2BRAIN_HOST }}
        REMOTE_USER: ${{ secrets.TEST_2BRAIN_USER }}
        REMOTE_PORT: ${{ secrets.TEST_2BRAIN_PORT }}
        ARGS: "-avzL"
        SOURCE: "social_media/dist/"
        TARGET: "server/www/depei.zhang/social_media"
        SCRIPT_BEFORE: |
          mkdir -p server/www/depei.zhang/social_media
          echo "Target directory created or already exists"
        SCRIPT_AFTER: |
          chmod -R 755 server/www/depei.zhang/social_media
          echo "Target directory permissions updated"